"""fee validation columns

Revision ID: 6231f021fc30
Revises: fc8697d93d9c
Create Date: 2026-09-23 21:54:50.970017

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6231f021fc30"
down_revision: str | Sequence[str] | None = "fc8697d93d9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fees", schema=None) as batch_op:
        batch_op.add_column(sa.Column("check_status", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("check_note", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("evidence", sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f("ix_fees_check_status"), ["check_status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fees_check_status"))
        batch_op.drop_column("evidence")
        batch_op.drop_column("check_note")
        batch_op.drop_column("check_status")

    # ### end Alembic commands ###
