"""conference online attendance

Revision ID: ada6fa96fe5e
Revises: 23945f9eeb75
Create Date: 2026-09-29 18:35:39.225249

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ada6fa96fe5e"
down_revision: str | Sequence[str] | None = "23945f9eeb75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("attendance", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conferences", schema=None) as batch_op:
        batch_op.drop_column("attendance")

    # ### end Alembic commands ###
