"""initial schema

Revision ID: fc8697d93d9c
Revises:
Create Date: 2026-09-23 09:04:06.932496

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc8697d93d9c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("acronym", sa.String(length=64), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("location_raw", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("abstract_deadline", sa.Date(), nullable=True),
        sa.Column("paper_deadline", sa.Date(), nullable=True),
        sa.Column("notification_date", sa.Date(), nullable=True),
        sa.Column("camera_ready_deadline", sa.Date(), nullable=True),
        sa.Column("registration_deadline", sa.Date(), nullable=True),
        sa.Column("homepage", sa.String(length=2048), nullable=True),
        sa.Column("registration_url", sa.String(length=2048), nullable=True),
        sa.Column("fee_min", sa.Float(), nullable=True),
        sa.Column("fee_max", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("field_sources", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conferences")),
    )
    with op.batch_alter_table("conferences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conferences_acronym"), ["acronym"], unique=False)
        batch_op.create_index(batch_op.f("ix_conferences_start_date"), ["start_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_conferences_status"), ["status"], unique=False)

    op.create_table(
        "fetched_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("final_url", sa.String(length=2048), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("body_path", sa.String(length=256), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fetched_pages")),
        sa.UniqueConstraint("url", name=op.f("uq_fetched_pages_url")),
    )
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scrape_runs")),
    )
    op.create_table(
        "fees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conference_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["conference_id"],
            ["conferences.id"],
            name=op.f("fk_fees_conference_id_conferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fees")),
    )
    with op.batch_alter_table("fees", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fees_conference_id"), ["conference_id"], unique=False)

    op.create_table(
        "raw_listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("acronym", sa.String(length=64), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("location_raw", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("homepage", sa.String(length=2048), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("abstract_deadline", sa.Date(), nullable=True),
        sa.Column("paper_deadline", sa.Date(), nullable=True),
        sa.Column("notification_date", sa.Date(), nullable=True),
        sa.Column("camera_ready_deadline", sa.Date(), nullable=True),
        sa.Column("registration_deadline", sa.Date(), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("in_window", sa.Boolean(), nullable=True),
        sa.Column("is_cs", sa.Boolean(), nullable=True),
        sa.Column("topic_reason", sa.String(length=255), nullable=True),
        sa.Column("conference_id", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conference_id"],
            ["conferences.id"],
            name=op.f("fk_raw_listings_conference_id_conferences"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_listings")),
        sa.UniqueConstraint("source", "source_id", name="uq_raw_listings_source_id"),
    )
    with op.batch_alter_table("raw_listings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_listings_conference_id"), ["conference_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_raw_listings_in_window"), ["in_window"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_listings_is_cs"), ["is_cs"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_listings_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_raw_listings_start_date"), ["start_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_listings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_listings_start_date"))
        batch_op.drop_index(batch_op.f("ix_raw_listings_source"))
        batch_op.drop_index(batch_op.f("ix_raw_listings_is_cs"))
        batch_op.drop_index(batch_op.f("ix_raw_listings_in_window"))
        batch_op.drop_index(batch_op.f("ix_raw_listings_conference_id"))

    op.drop_table("raw_listings")
    with op.batch_alter_table("fees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fees_conference_id"))

    op.drop_table("fees")
    op.drop_table("scrape_runs")
    op.drop_table("fetched_pages")
    with op.batch_alter_table("conferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conferences_status"))
        batch_op.drop_index(batch_op.f("ix_conferences_start_date"))
        batch_op.drop_index(batch_op.f("ix_conferences_acronym"))

    op.drop_table("conferences")
    # ### end Alembic commands ###
