"""conference publication history

Revision ID: 23945f9eeb75
Revises: 446e4e41746b
Create Date: 2026-09-29 17:20:56.357829

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23945f9eeb75"
down_revision: str | Sequence[str] | None = "446e4e41746b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("history", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conferences", schema=None) as batch_op:
        batch_op.drop_column("history")

    # ### end Alembic commands ###
