"""conference enriched_at

Revision ID: 446e4e41746b
Revises: 6231f021fc30
Create Date: 2026-09-23 22:25:58.926344

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "446e4e41746b"
down_revision: str | Sequence[str] | None = "6231f021fc30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("enriched_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conferences", schema=None) as batch_op:
        batch_op.drop_column("enriched_at")

    # ### end Alembic commands ###
